ENVIRONMENT:
  MAX_EPISODE_STEPS: 1000
SIMULATOR:
  AGENT_0:
    SENSORS: []
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    COMPRESS_TEXTURES: False
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2
  SENSORS: ['POINTGOAL_SENSOR', 'GPS_AND_COMPASS', 'DIST_TO_GOAL']
  POINTGOAL_SENSOR:
    TYPE: PointGoalSensor
    GOAL_FORMAT: POLAR
    SENSOR_TYPE: DENSE
    COORDINATE_SYSTEM: global
  MEASUREMENTS: ['SPL']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.2
DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  POINTNAVV1:
    DATA_PATH: 'data/datasets/pointnav/mdp/v1/{split}/{split}.json.gz'
    CONTENT_SCENES: ["*"]
