ENVIRONMENT:
  MAX_EPISODE_STEPS: 1000
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    COMPRESS_TEXTURES: False
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.15
  SENSORS: ['POINTGOAL_SENSOR']
  POINTGOAL_SENSOR:
    TYPE: PointGoalSensor
    GOAL_FORMAT: POLAR
    SENSOR_TYPE: DENSE
  MEASUREMENTS: ['SPL']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.15
DATASET:
  TYPE: PointNavOTF-v1
  SPLIT: train
  POINTNAVV1:
    DATA_PATH: 'data/datasets/pointnav/mp3d-gibson-public/v1/{split}/{split}.json.gz'
    CONTENT_SCENES: ["*"]
